"
A FailSafeDebugSessionTest is a test class for testing the behavior of FailSafeDebugSession
"
Class {
	#name : #FailSafeDebugSessionTest,
	#superclass : #TestCase,
	#category : #'FailSafeDebugger-Tests-Core'
}

{ #category : #test }
FailSafeDebugSessionTest >> testPrivateStepToFirstInterestingBytecodeIn [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
FailSafeDebugSessionTest >> testStepInto [

	self flag: #toImplement.
	self assert: false
]
